"""Git-backed version control for the entire ``data/`` tree.

Auto-initializes a private repo at ``<data_root>/.git`` (separate from any user
project repos under ``data/projects/<id>/``). Every meaningful state change in
Blackboard — board edits, role/key overrides, project lifecycle, manual
checkpoints — auto-commits to this repo with a structured message and a `kind`
trailer. The result is a complete, queryable timeline with safe rollback.

Design choices:
  - We **shell out to git** (already a hard dep for worktrees) instead of pulling
    in GitPython. Tiny, no extra dependency, no Python-version friction.
  - Default rollback mode is ``revert`` (creates a new commit that undoes the
    changes). ``hard`` mode is supported but never used by the API by default.
  - Commits use a "Blackboard <blackboard@local>" identity to keep them visually
    distinct from user commits in any nested project repos.
  - Auto-commits are best-effort: if git is missing, the operation logs a warning
    and continues. The system never crashes for lack of version control.
  - Sub-repositories (``data/projects/<id>/.git`` from coding worktrees) are
    excluded by writing a ``.gitignore`` at ``data/`` root that ignores
    ``projects/*/.worktrees/`` and ``projects/*/.git``.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from threading import Lock
from typing import Any, Dict, List, Optional, Tuple

from blackboard.kernel.logger import get_logger

logger = get_logger("workspace.version_control")


_AUTHOR_NAME = "Blackboard"
_AUTHOR_EMAIL = "blackboard@local"

_DATA_GITIGNORE = """\
# Auto-generated by Blackboard's data version control.
# Excludes nested repos and ephemeral artifacts so the data/ history is clean.
projects/*/.worktrees/
projects/*/.git/
projects/*/.git
**/.DS_Store
**/Thumbs.db
**/__pycache__/
"""


@dataclass
class Commit:
    sha: str
    short_sha: str
    author: str
    timestamp: int
    subject: str
    kind: str  # parsed from "Kind: <kind>" trailer; "" if none
    files: List[str]


# Resolved git executable. Sentinel "" means "not resolved yet", None means "unavailable".
_GIT_BIN: Optional[str] = ""


def _resolve_git_bin() -> Optional[str]:
    """Locate the git executable. Tries PATH first, then common Windows install paths."""
    global _GIT_BIN
    if _GIT_BIN != "":
        return _GIT_BIN
    found = shutil.which("git")
    if not found and os.name == "nt":
        for candidate in (
            r"C:\Program Files\Git\cmd\git.exe",
            r"C:\Program Files (x86)\Git\cmd\git.exe",
            r"C:\Program Files\Git\bin\git.exe",
        ):
            if Path(candidate).exists():
                found = candidate
                logger.info("[vcs] git found via fallback: %s", candidate)
                break
    _GIT_BIN = found or None
    return _GIT_BIN


def _git(args: List[str], cwd: Path, *, timeout: int = 30, input_text: Optional[str] = None) -> Tuple[int, str, str]:
    git_bin = _resolve_git_bin() or "git"
    try:
        r = subprocess.run(
            [git_bin, *args],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=timeout,
            input=input_text,
        )
        return r.returncode, r.stdout, r.stderr
    except FileNotFoundError:
        return 127, "", "git not installed"
    except subprocess.TimeoutExpired:
        return 124, "", f"git timed out: {' '.join(args)}"
    except Exception as exc:
        return 1, "", str(exc)


class DataVersionControl:
    """Owns the ``<data_root>/.git`` repo. Thread-safe via internal lock."""

    def __init__(self, data_root: Path) -> None:
        self.data_root = Path(data_root).resolve()
        self._lock = Lock()
        self._available: Optional[bool] = None  # cached availability after init

    # ── Lifecycle ────────────────────────────────────────────────

    def ensure_initialized(self) -> bool:
        """Idempotently initialize ``data/.git`` and write the ``.gitignore`` filter.

        Returns ``True`` when the repo is usable, ``False`` if git isn't installed
        or initialization failed. Cached after first call.
        """
        if self._available is not None:
            return self._available
        if _resolve_git_bin() is None:
            logger.warning("[vcs] git not found on PATH or in standard install locations — version control disabled")
            self._available = False
            return False
        self.data_root.mkdir(parents=True, exist_ok=True)
        with self._lock:
            git_dir = self.data_root / ".git"
            if not git_dir.exists():
                code, _, err = _git(["init", "-q", "-b", "main"], cwd=self.data_root, timeout=15)
                if code != 0:
                    logger.warning("[vcs] git init failed: %s", err.strip())
                    self._available = False
                    return False
                # Per-repo identity so we don't depend on global ~/.gitconfig.
                _git(["config", "user.name", _AUTHOR_NAME], cwd=self.data_root)
                _git(["config", "user.email", _AUTHOR_EMAIL], cwd=self.data_root)
                # Avoid line-ending churn between Windows + POSIX.
                _git(["config", "core.autocrlf", "input"], cwd=self.data_root)
            ignore_path = self.data_root / ".gitignore"
            if not ignore_path.exists():
                ignore_path.write_text(_DATA_GITIGNORE, encoding="utf-8")
                _git(["add", ".gitignore"], cwd=self.data_root)
            # Make sure HEAD has at least one commit so log/diff/revert work.
            code, head_out, _ = _git(["rev-parse", "--verify", "HEAD"], cwd=self.data_root)
            if code != 0:
                _git(["add", "-A"], cwd=self.data_root)
                _git(
                    ["commit", "-q", "--allow-empty", "-m", "Initial Blackboard data snapshot\n\nKind: vcs.init"],
                    cwd=self.data_root, timeout=20,
                )
        self._available = True
        return True

    # ── Commit / history ─────────────────────────────────────────

    def commit(self, message: str, *, kind: str = "", paths: Optional[List[str]] = None) -> Optional[str]:
        """Stage and commit. Returns the new SHA, or ``None`` if nothing changed.

        ``paths`` may be relative or absolute; absolutes outside ``data_root`` are dropped.
        ``kind`` is appended as a "Kind: <kind>" trailer for later filtering.
        """
        if not self.ensure_initialized():
            return None
        rels = self._normalize_paths(paths)
        with self._lock:
            if rels:
                _git(["add", "--", *rels], cwd=self.data_root)
            else:
                _git(["add", "-A"], cwd=self.data_root)
            # Skip the commit if there's nothing staged.
            code, _, _ = _git(["diff", "--cached", "--quiet"], cwd=self.data_root)
            if code == 0:
                return None
            full = (message or "Update").splitlines()[0].strip() or "Update"
            body = ""
            if "\n" in (message or ""):
                body = "\n\n" + "\n".join((message or "").splitlines()[1:]).strip()
            if kind:
                body += f"\n\nKind: {kind}"
            commit_msg = full + body
            code, out, err = _git(["commit", "-q", "-m", commit_msg], cwd=self.data_root, timeout=20)
            if code != 0:
                logger.warning("[vcs] commit failed: %s", (err or out).strip())
                return None
            code, sha, _ = _git(["rev-parse", "HEAD"], cwd=self.data_root)
            return sha.strip() if code == 0 else None

    def history(self, *, path: Optional[str] = None, limit: int = 50) -> List[Commit]:
        """Return up to ``limit`` commits, newest first. Optionally filtered by path.

        Uses three layers of ASCII control chars to be unambiguous against bodies
        that contain newlines:
          - ``\\x1e`` (record separator) between commits
          - ``\\x1d`` (group separator) between the field block and the file list
          - ``\\x1f`` (unit separator) between fields within the field block
        """
        if not self.ensure_initialized():
            return []
        FIELD = "\x1f"
        GROUP = "\x1d"
        RECORD = "\x1e"
        fmt = RECORD + FIELD.join(["%H", "%h", "%an", "%at", "%s", "%b"]) + GROUP
        args = ["log", f"--max-count={int(max(1, min(limit, 500)))}", f"--pretty=format:{fmt}", "--name-only"]
        if path:
            args.extend(["--", path])
        code, out, err = _git(args, cwd=self.data_root, timeout=20)
        if code != 0 or not out:
            return []
        out_commits: List[Commit] = []
        for raw_record in out.split(RECORD):
            record = raw_record.strip("\n")
            if not record:
                continue
            head, sep, files_block = record.partition(GROUP)
            if not sep:
                # Older fallback: assume no files.
                head, files_block = record, ""
            parts = head.split(FIELD)
            if len(parts) < 5:
                continue
            sha, short_sha, author, ts, subject = parts[0], parts[1], parts[2], parts[3], parts[4]
            body = parts[5] if len(parts) > 5 else ""
            kind = ""
            for line in body.splitlines():
                line = line.strip()
                if line.lower().startswith("kind:"):
                    kind = line.split(":", 1)[1].strip()
                    break
            files = [f for f in files_block.splitlines() if f.strip()]
            try:
                ts_int = int(ts)
            except Exception:
                ts_int = 0
            out_commits.append(Commit(
                sha=sha, short_sha=short_sha, author=author, timestamp=ts_int,
                subject=subject, kind=kind, files=files,
            ))
        return out_commits

    def show_diff(self, sha: str, *, with_paths: bool = True) -> Dict[str, Any]:
        """Return a unified diff + the list of files changed for a single commit."""
        if not self.ensure_initialized():
            return {"sha": sha, "diff": "", "files": []}
        sha = sha.strip()
        if not sha:
            return {"sha": "", "diff": "", "files": []}
        files: List[str] = []
        if with_paths:
            code, out, _ = _git(["show", "--name-only", "--pretty=format:", sha], cwd=self.data_root)
            if code == 0:
                files = [f for f in out.splitlines() if f.strip()]
        code, diff_out, err = _git(["show", "--no-color", sha], cwd=self.data_root, timeout=30)
        if code != 0:
            return {"sha": sha, "diff": "", "files": files, "error": err.strip()}
        return {"sha": sha, "diff": diff_out, "files": files}

    # ── Rollback ─────────────────────────────────────────────────

    def rollback(self, sha: str, *, mode: str = "revert") -> Dict[str, Any]:
        """Undo a commit.

        ``mode='revert'`` (default, safe): creates a new commit that inverts the
        target, leaving history intact.
        ``mode='hard'`` (destructive): resets HEAD back to ``sha`` and discards
        every change after it. Only use when the operator explicitly chooses it.
        """
        if not self.ensure_initialized():
            return {"ok": False, "error": "version control unavailable"}
        sha = sha.strip()
        if not sha:
            return {"ok": False, "error": "sha required"}
        if mode not in ("revert", "hard"):
            return {"ok": False, "error": f"unknown mode: {mode}"}
        with self._lock:
            if mode == "revert":
                code, out, err = _git(
                    ["revert", "--no-edit", sha],
                    cwd=self.data_root, timeout=30,
                )
                if code != 0:
                    # Abort any in-progress revert state to leave the repo clean.
                    _git(["revert", "--abort"], cwd=self.data_root)
                    return {"ok": False, "error": (err or out).strip() or "revert failed"}
                code, new_sha, _ = _git(["rev-parse", "HEAD"], cwd=self.data_root)
                return {"ok": True, "mode": "revert", "new_sha": new_sha.strip(), "reverted": sha}
            else:  # hard
                code, _, err = _git(["reset", "--hard", sha], cwd=self.data_root, timeout=30)
                if code != 0:
                    return {"ok": False, "error": err.strip() or "hard reset failed"}
                code, head_sha, _ = _git(["rev-parse", "HEAD"], cwd=self.data_root)
                return {"ok": True, "mode": "hard", "new_sha": head_sha.strip(), "rolled_back_to": sha}

    # ── Tags (named checkpoints) ─────────────────────────────────

    def tag(self, name: str, *, sha: Optional[str] = None, message: str = "") -> Dict[str, Any]:
        """Create an annotated tag. ``sha`` defaults to HEAD."""
        if not self.ensure_initialized():
            return {"ok": False, "error": "version control unavailable"}
        name = (name or "").strip()
        if not name:
            return {"ok": False, "error": "tag name required"}
        args = ["tag", "-a", name, "-m", message or name]
        if sha:
            args.append(sha.strip())
        code, _, err = _git(args, cwd=self.data_root)
        if code != 0:
            return {"ok": False, "error": err.strip() or "tag failed"}
        return {"ok": True, "name": name}

    def list_tags(self) -> List[Dict[str, Any]]:
        if not self.ensure_initialized():
            return []
        code, out, _ = _git(["tag", "--format=%(refname:short)\x1f%(objectname)\x1f%(taggerdate:unix)\x1f%(subject)"], cwd=self.data_root)
        if code != 0:
            return []
        tags: List[Dict[str, Any]] = []
        for line in out.splitlines():
            parts = line.split("\x1f")
            if len(parts) < 4 or not parts[0].strip():
                continue
            try:
                ts = int(parts[2]) if parts[2].strip() else 0
            except Exception:
                ts = 0
            tags.append({"name": parts[0], "sha": parts[1], "ts": ts, "message": parts[3]})
        return tags

    # ── Helpers ──────────────────────────────────────────────────

    def head(self) -> str:
        if not self.ensure_initialized():
            return ""
        code, out, _ = _git(["rev-parse", "HEAD"], cwd=self.data_root)
        return out.strip() if code == 0 else ""

    def status(self) -> Dict[str, Any]:
        """Return a lightweight repo status: HEAD sha, branch, dirty flag."""
        if not self.ensure_initialized():
            return {"available": False, "head": "", "branch": "", "dirty": False, "commits": 0}
        code, head_sha, _ = _git(["rev-parse", "HEAD"], cwd=self.data_root)
        code_b, branch, _ = _git(["rev-parse", "--abbrev-ref", "HEAD"], cwd=self.data_root)
        code_d, dirty_out, _ = _git(["status", "--porcelain"], cwd=self.data_root)
        code_c, count, _ = _git(["rev-list", "--count", "HEAD"], cwd=self.data_root)
        return {
            "available": True,
            "head": head_sha.strip(),
            "branch": branch.strip() if code_b == 0 else "",
            "dirty": bool(dirty_out.strip()) if code_d == 0 else False,
            "commits": int(count.strip()) if code_c == 0 and count.strip().isdigit() else 0,
        }

    def _normalize_paths(self, paths: Optional[List[str]]) -> List[str]:
        if not paths:
            return []
        out: List[str] = []
        for p in paths:
            if not p:
                continue
            target = Path(p)
            if not target.is_absolute():
                target = self.data_root / target
            try:
                rel = target.resolve().relative_to(self.data_root)
            except ValueError:
                # Path is outside data_root — silently skip rather than committing
                # something the user didn't intend.
                continue
            out.append(str(rel).replace("\\", "/"))
        return out


class ExistingRepoVersionControl(DataVersionControl):
    def ensure_initialized(self) -> bool:
        if self._available is not None:
            return self._available
        if _resolve_git_bin() is None:
            logger.warning("[vcs] git not found on PATH or in standard install locations — version control disabled")
            self._available = False
            return False
        if not self.data_root.exists():
            self._available = False
            return False
        cwd = self.data_root if self.data_root.is_dir() else self.data_root.parent
        code, out, err = _git(["rev-parse", "--show-toplevel"], cwd=cwd)
        if code != 0 or not out.strip():
            logger.debug("[vcs] existing repo unavailable at %s: %s", self.data_root, (err or out).strip())
            self._available = False
            return False
        self.data_root = Path(out.strip()).resolve()
        self._available = True
        return True


def resolve_git_root(path: Path | str) -> Optional[Path]:
    target = Path(path).resolve()
    if not target.exists():
        return None
    cwd = target if target.is_dir() else target.parent
    code, out, _ = _git(["rev-parse", "--show-toplevel"], cwd=cwd)
    if code != 0 or not out.strip():
        return None
    try:
        return Path(out.strip()).resolve()
    except Exception:
        return None


def get_existing_repo_version_control(path: Path | str) -> Optional[ExistingRepoVersionControl]:
    root = resolve_git_root(path)
    if root is None:
        return None
    vcs = ExistingRepoVersionControl(root)
    return vcs if vcs.ensure_initialized() else None


# ── Singleton for the running app ──────────────────────────────────

_singleton: Optional[DataVersionControl] = None


def init_version_control(data_root: Path) -> DataVersionControl:
    global _singleton
    _singleton = DataVersionControl(data_root)
    _singleton.ensure_initialized()
    return _singleton


def get_version_control() -> Optional[DataVersionControl]:
    return _singleton


def commit_safely(message: str, *, kind: str = "", paths: Optional[List[str]] = None) -> Optional[str]:
    """Best-effort commit shortcut for callers that don't care if VCS is unavailable.

    Also fires a ``vcs.commit`` event on the kernel bus so the audit log + UI
    stay in sync. The event payload contains the SHA, the parsed kind, the
    short subject, and the file paths touched (never the diff itself, which
    callers can fetch on demand).
    """
    vcs = get_version_control()
    if vcs is None:
        return None
    try:
        sha = vcs.commit(message, kind=kind, paths=paths)
    except Exception as exc:
        logger.debug("[vcs] commit_safely swallow: %s", exc)
        return None
    if not sha:
        return None
    # Best-effort bus emit — schedule on the running loop if there is one.
    try:
        import asyncio
        from blackboard.kernel.bus import get_bus
        payload = {
            "sha": sha,
            "short_sha": sha[:8],
            "kind": kind or "",
            "subject": (message or "").splitlines()[0][:200],
            "paths": list(paths or []),
        }
        try:
            loop = asyncio.get_running_loop()
            loop.create_task(get_bus().emit("vcs.commit", payload))
        except RuntimeError:
            # No running loop (called from a sync context) — skip the event silently.
            pass
    except Exception:
        pass
    return sha


def commit_dict(c: Commit) -> Dict[str, Any]:
    return asdict(c)
